spring:
  profiles:
    active: dev

info:
  app:
    name: Qred Payment Service
    version: 0.0.1
    description: Service for handling payment operations.

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

logging:
  level:
    org:
      comeon: DEBUG
      hibernate: DEBUG
      hibernate.type.descriptor.sql: TRACE

use:
  virtual:
    threads: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
