spring:
  datasource:
    url: jdbc:h2:mem:gamedb
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
  h2:
    console:
      enabled: true
